spring:
    application:
        name: caring
    profiles:
      active: dev

# ğŸŒ ì„œë²„ ì„¤ì •
server:
  port: 8080
  servlet:
    context-path: /

# ğŸ“ ë¡œê¹… ì„¤ì •
logging:
  level:
    com.caring.caringbackend: INFO
    org.springframework.web: DEBUG
    p6spy: INFO  # P6Spy ë¡œê·¸ ë ˆë²¨

# P6Spy ì„¤ì •
decorator:
  datasource:
    p6spy:
      enable-logging: true
