spring:
    application:
        name: caring
    profiles:
      active: dev

# ğŸŒ ì„œë²„ ì„¤ì •
server:
  port: 8080
  servlet:
    context-path: /

# ğŸ“ ë¡œê¹… ì„¤ì •
logging:
  level:
    com.caring.caringbackend: INFO
    org.springframework.web: DEBUG
